# Generated by Django 3.1.1 on 2020-09-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PTFdados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SBICS', models.CharField(blank=True, max_length=200, null=True, verbose_name='Classificação nova SBICS')),
                ('OLD', models.CharField(blank=True, max_length=200, null=True, verbose_name='Classificação antiga')),
                ('LAT', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('LON', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('MUN', models.CharField(blank=True, max_length=60, null=True, verbose_name='Municipio')),
                ('GEOCOD', models.IntegerField(blank=True, null=True, verbose_name='codigo do municipio IBGE')),
                ('T_ARE', models.FloatField(blank=True, null=True, verbose_name='Total de areia* em g/kg')),
                ('AGRO', models.FloatField(blank=True, null=True, verbose_name='Total de areia grossa (2 - 0,2 mm) em g/kg')),
                ('AFIN', models.FloatField(blank=True, null=True, verbose_name='Total de areia Fina (0,2 - 0,05 mm) em g/kg')),
                ('SILT', models.FloatField(blank=True, null=True, verbose_name='Total de Silte (0,05 - 0,002 mm) em g/kg')),
                ('ARG', models.FloatField(blank=True, null=True, verbose_name='Total de Argila (< 0,002 mm) em g/kg')),
                ('SOLO', models.FloatField(blank=True, null=True, verbose_name='Densidade do Solo em g/dm³')),
                ('C_ORG', models.FloatField(blank=True, null=True, verbose_name='Total Carbono Orgânico* em g/kg')),
                ('M_ORG', models.FloatField(blank=True, null=True)),
                ('OLIV', models.FloatField(blank=True, null=True)),
                ('B_ZU', models.FloatField(blank=True, null=True)),
                ('B_TT', models.FloatField(blank=True, null=True, verbose_name='Theta a 33mm')),
                ('B_PC', models.FloatField(blank=True, null=True, verbose_name='Theta a 1500mm')),
                ('B_ALPHA', models.FloatField(blank=True, null=True)),
                ('B_N', models.FloatField(blank=True, null=True)),
                ('B_THETAS', models.FloatField(blank=True, null=True)),
                ('B_TETHAR', models.FloatField(blank=True, null=True)),
                ('B_AD', models.FloatField(blank=True, null=True)),
                ('T_ZU', models.FloatField(blank=True, null=True)),
                ('T_TT', models.FloatField(blank=True, null=True)),
                ('T_PC', models.FloatField(blank=True, null=True)),
                ('T_ALPHA', models.FloatField(blank=True, null=True)),
                ('T_N', models.FloatField(blank=True, null=True)),
                ('T_THETAR', models.FloatField(blank=True, null=True)),
                ('T_TETHAS', models.FloatField(blank=True, null=True)),
                ('T_AD', models.FloatField(blank=True, null=True)),
                ('escolha', models.CharField(choices=[('ct', 'Classes Texturais'), ('asa', 'Areia, silte e argila'), ('asad', 'Areia, silte e argila e densidade'), ('asadtt', 'Areia, Silt, Argila, Densidade e AD 33kPa (TH33)'), ('asadpc', 'Areia, Silt, Argila e Densidade e AD 1500kPa (TH1500)')], default='ct', max_length=300, verbose_name='escolha uma opção de calculo:')),
            ],
        ),
    ]
