# Generated by Django 3.0.3 on 2020-02-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PTFdados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SBICS', models.CharField(blank=True, max_length=200, null=True, verbose_name='Classificacao nova SBICS')),
                ('OLD', models.CharField(blank=True, max_length=200, null=True, verbose_name='Classificacao antiga')),
                ('LAT', models.FloatField(blank=True, null=True, verbose_name='Latitude*')),
                ('LON', models.FloatField(blank=True, null=True, verbose_name='Longitude*')),
                ('MUN', models.CharField(blank=True, max_length=60, null=True, verbose_name='Municipio*')),
                ('GEOCOD', models.IntegerField(blank=True, null=True, verbose_name='codigo do municipio IBGE*')),
                ('T_ARE', models.FloatField(blank=True, null=True, verbose_name='Total de areia* em g/kg')),
                ('AGRO', models.FloatField(blank=True, null=True, verbose_name='Total de areia grossa*(2 - 0,2 mm) em g/kg')),
                ('AFIN', models.FloatField(blank=True, null=True, verbose_name='Total de areia Fina* (0,2 - 0,05 mm) em g/kg')),
                ('SILT', models.FloatField(blank=True, null=True, verbose_name='Total de Silte* (0,05 - 0,002 mm) em g/kg')),
                ('ARG', models.FloatField(blank=True, null=True, verbose_name='Total de Argila* (< 0,002 mm) em g/kg')),
                ('SOLO', models.FloatField(blank=True, null=True, verbose_name='Densidade do Solo* em g/dm³')),
                ('C_ORG', models.FloatField(blank=True, null=True, verbose_name='Total Carbono Orgânico* em g/kg')),
                ('M_ORG', models.FloatField(blank=True, null=True)),
                ('OLIV', models.FloatField(blank=True, null=True)),
                ('B_ZU', models.FloatField(blank=True, null=True)),
                ('B_TT', models.FloatField(blank=True, null=True)),
                ('B_PC', models.FloatField(blank=True, null=True)),
                ('B_ALPHA', models.FloatField(blank=True, null=True)),
                ('B_N', models.FloatField(blank=True, null=True)),
                ('B_THETAS', models.FloatField(blank=True, null=True)),
                ('B_TETHAR', models.FloatField(blank=True, null=True)),
                ('B_AD', models.FloatField(blank=True, null=True)),
                ('T_ZU', models.FloatField(blank=True, null=True)),
                ('T_TT', models.FloatField(blank=True, null=True)),
                ('T_PC', models.FloatField(blank=True, null=True)),
                ('T_ALPHA', models.FloatField(blank=True, null=True)),
                ('T_N', models.FloatField(blank=True, null=True)),
                ('T_THETAR', models.FloatField(blank=True, null=True)),
                ('T_TETHAS', models.FloatField(blank=True, null=True)),
                ('T_AD', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
