# Generated by Django 3.0.3 on 2020-03-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aguadisponivel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptfdados',
            name='escolha',
            field=models.CharField(choices=[('ct', 'Classes Texturais'), ('asa', 'Areia, silte e argila'), ('asad', 'Areia, silte e argila e densidade'), ('asadtt', 'Areia, Silt, Argila, Densidade e AD 33kPa (TH33)'), ('asadpc', 'Areia, Silt, Argila e Densidade e AD 1500kPa (TH1500)')], default='ct', max_length=300, verbose_name='escolha uma opção de calculo:'),
        ),
        migrations.AlterField(
            model_name='ptfdados',
            name='AFIN',
            field=models.FloatField(blank=True, null=True, verbose_name='Total de areia Fina (0,2 - 0,05 mm) em g/kg'),
        ),
        migrations.AlterField(
            model_name='ptfdados',
            name='AGRO',
            field=models.FloatField(blank=True, null=True, verbose_name='Total de areia grossa (2 - 0,2 mm) em g/kg'),
        ),
        migrations.AlterField(
            model_name='ptfdados',
            name='ARG',
            field=models.FloatField(blank=True, null=True, verbose_name='Total de Argila (< 0,002 mm) em g/kg'),
        ),
        migrations.AlterField(
            model_name='ptfdados',
            name='GEOCOD',
            field=models.IntegerField(blank=True, null=True, verbose_name='codigo do municipio IBGE'),
        ),
        migrations.AlterField(
            model_name='ptfdados',
            name='LAT',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='ptfdados',
            name='LON',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='ptfdados',
            name='MUN',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='ptfdados',
            name='OLD',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Classificação antiga'),
        ),
        migrations.AlterField(
            model_name='ptfdados',
            name='SBICS',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Classificação nova SBICS'),
        ),
        migrations.AlterField(
            model_name='ptfdados',
            name='SILT',
            field=models.FloatField(blank=True, null=True, verbose_name='Total de Silte (0,05 - 0,002 mm) em g/kg'),
        ),
        migrations.AlterField(
            model_name='ptfdados',
            name='SOLO',
            field=models.FloatField(blank=True, null=True, verbose_name='Densidade do Solo em g/dm³'),
        ),
    ]
