# Generated by Django 3.1 on 2020-09-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aguadisponivel', '0002_auto_20200316_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptfdados',
            name='B_PC',
            field=models.FloatField(blank=True, null=True, verbose_name='Theta a 1500mm'),
        ),
        migrations.AlterField(
            model_name='ptfdados',
            name='B_TT',
            field=models.FloatField(blank=True, null=True, verbose_name='Theta a 33mm'),
        ),
    ]
